services:
  wechat-robot-document:
    image: registry.cn-shenzhen.aliyuncs.com/houhou/wechat-robot-document:latest
    container_name: wechat-robot-document
    ports:
      - "4100:80"
    restart: unless-stopped